name: "Compliance of gx-scs"

on:
  push:
    branches:
    - main
    paths:
      - Tests/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  check-gx-scs:
    uses: ./.github/workflows/scs-compliance-check.yml
    with:
      cloud: "gx-scs"
      secret_name: "OS_PASSWORD_GXSCS"
    secrets: inherit