---
name: Synchronize SCS Docs

on:
  workflow_call:
    secrets:
      PAT:
        required: true
  workflow_dispatch:

jobs:
  provide_repos_json:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout the docusaurus repo (B)
        uses: actions/checkout@v3

      - name: Set Matrix
        id: set-matrix
        run: |
          REPOS=$(echo $(cat ././docs.package.json) | sed 's/ //g' )
          echo "::set-output name=matrix::$REPOS"
  
  sync_repos:
    needs: provide_repos_json
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: 
        repos: ${{ fromJson(needs.provide_repos_json.outputs.matrix) }}
    steps: 
      - name: checkout the docusaurus repo (B)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
  
      - name: clone repo A which is about to be synchronized
        uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: ${{matrix.repos.repo}}
          path: 'repo_to_be_edited'

      - name: remove git folders from A
        run: |
          rm -rf $(pwd)/repo_to_be_edited/.git

      - name: remove README.md files from A
        run: |
          find $(pwd)/repo_to_be_edited -name "README.md" | xargs rm -f

      - name: create docusaurus subdirectory
        run: |
          mkdir $(pwd)/${{matrix.repos.target}}/${{matrix.repos.label}} || true

      - name: copy docs content from A to B
        run: |
          cp -r $(pwd)/repo_to_be_edited/${{matrix.repos.source}} $(pwd)/${{matrix.repos.target}}/${{matrix.repos.label}}
          
      - name: remove repo A
        run: |
          rm -rf $(pwd)/repo_to_be_edited/

      - name: commit and push B
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'bot@scs'
          committer_name: Action Bot
          commit: --signoff
          message: "distill ${{matrix.repos.repo}}"
          push: true
          pull: --rebase --autostash
